# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nx Affected CI

on:
  pull_request:
    branches: [ main ]

jobs:

  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 16.x
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
  build:

    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git fetch origin main
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: cache-node-modules-${{ hashFiles('package-lock.json') }}
    - run: npm run affected:build --with-deps --parallel -- --base=remotes/origin/main
